env:
  global:
    - BUILD_DOCS=false
    - TEST_ARGS=--no-pep8

language: python

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.2
    - python: 3.3
    - python: 3.4
    - python: 2.7
      env: TEST_ARGS=--pep8
    - python: 2.7
      env: BUILD_DOCS=true

install:
  - pip install -q --use-mirrors nose python-dateutil numpy pep8 pyparsing pillow
  - sudo apt-get update && sudo apt-get -qq install inkscape libav-tools
  - if [[ $BUILD_DOCS == true ]]; then pip install sphinx numpydoc linkchecker; fi
  - python setup.py install

script:
  # The number of processes is hardcoded, because using too many causes the
  # Travis VM to run out of memory (since so many copies of inkscape and
  # ghostscript are running at the same time).
  - echo Testing using 8 processes
  # Generate the font caches in a single process before starting the
  # multiple processes
  - python -c "from matplotlib import font_manager"
  - if [[ $BUILD_DOCS == false ]]; then mkdir ../tmp_test_dir; fi
  - if [[ $BUILD_DOCS == false ]]; then cd ../tmp_test_dir; fi
  - if [[ $BUILD_DOCS == false ]]; then python ../matplotlib/tests.py -sv --processes=8 --process-timeout=300 $TEST_ARGS; fi
  - if [[ $BUILD_DOCS == true ]]; then cd doc; python make.py html --small; fi
  # We don't build the LaTeX docs here, so linkchecker will complain
  - if [[ $BUILD_DOCS == true ]]; then touch build/html/Matplotlib.pdf; fi
  - if [[ $BUILD_DOCS == true ]]; then linkchecker build/html/index.html; fi

after_failure:
  - tar cjf result_images.tar.bz2 result_images
  - if [[ $TRAVIS_PULL_REQUEST == false ]]; then gem install travis-artifacts; fi
  - if [[ $TRAVIS_PULL_REQUEST == false ]]; then travis-artifacts upload --path result_images.tar.bz2; fi
  - if [[ $TRAVIS_PULL_REQUEST != false ]]; then echo "The result images will only be uploaded if they are on the matplotlib/matplotlib repo - this is for security reasons to prevent arbitrary PRs echoing security details." else echo https://s3.amazonaws.com/matplotlib-test-results/artifacts/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/result_images.tar.bz2; fi
